export const roles = {
  customer: "customer",
  vendor: "vendor",
  admin: "admin",
  super_admin: "super_admin",
  product_manager: "product_manager",
} as const;
export const permissions = {
  products_view: "products.view",
  products_create: "products.create",
  products_update: "products.update",
  products_delete: "products.delete",
  products_publish: "products.publish",
  vendors_view: "vendors.view",
  vendors_create: "vendors.create",
  vendors_update: "vendors.update",
  vendors_delete: "vendors.delete",
  vendors_approve: "vendors.approve",
  vendors_suspend: "vendors.suspend",
  categories_view: "categories.view",
  categories_create: "categories.create",
  categories_update: "categories.update",
  categories_delete: "categories.delete",
  brands_view: "brands.view",
  brands_create: "brands.create",
  brands_update: "brands.update",
  orders_view: "orders.view",
  orders_update: "orders.update",
  customers_view: "customers.view",
  customers_update: "customers.update",
  customers_suspend: "customers.suspend",
  services_view: "services.view",
  services_create: "services.create",
  services_update: "services.update",
  services_delete: "services.delete",
  inventory_view: "inventory.view",
  inventory_update: "inventory.update",
  settings_manage: "settings.manage",
  vendor_profile_view: "vendor_profile.view",
  vendor_profile_update: "vendor_profile.update",
} as const;
export const rolePermissions = {
  customer: [],
  vendor: [
    permissions.products_view,
    permissions.products_create,
    permissions.products_update,
    permissions.orders_view,
    permissions.brands_view,
    permissions.brands_create,
    permissions.inventory_view,
    permissions.inventory_update,
    permissions.vendor_profile_view,
    permissions.vendor_profile_update,
  ],
  product_manager: [
    permissions.products_view,
    permissions.products_create,
    permissions.products_update,
    permissions.products_delete,
    permissions.products_publish,
    permissions.categories_view,
    permissions.categories_create,
    permissions.categories_update,
    permissions.categories_delete,
    permissions.inventory_view,
    permissions.inventory_update,
  ],
  admin: [
    permissions.products_view,
    permissions.products_create,
    permissions.products_update,
    permissions.products_delete,
    permissions.products_publish,
    permissions.vendors_view,
    permissions.vendors_create,
    permissions.vendors_update,
    permissions.vendors_delete,
    permissions.vendors_approve,
    permissions.vendors_suspend,
    permissions.categories_view,
    permissions.categories_create,
    permissions.categories_update,
    permissions.categories_delete,
    permissions.brands_view,
    permissions.brands_create,
    permissions.brands_update,
    permissions.orders_view,
    permissions.orders_update,
    permissions.customers_view,
    permissions.customers_update,
    permissions.customers_suspend,
    permissions.services_view,
    permissions.services_create,
    permissions.services_update,
    permissions.services_delete,
    permissions.inventory_view,
    permissions.inventory_update,
  ],
  super_admin: Object.values(permissions),
} as const;
